# Generated by Django 4.2 on 2023-04-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Вид оплаты',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment', verbose_name='Вид оплаты')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='Размер')),
            ],
        ),
    ]
