# Generated by Django 4.2 on 2023-04-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_payment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('item',), 'verbose_name_plural': 'Заказы'},
        ),
    ]
